version: '3.8'

services: 
  backend:
    build: ./backend
    ports: 
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules  # prevents override
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules  # prevents override
    depends_on:
      - backend

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: Cluster0
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
